/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lybsanzreldqcjuegcqj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5YnNhbnpyZWxkcWNqdWVnY3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU5NTQ4NzEsImV4cCI6MjA4MTUzMDg3MX0.2y60H79Q4eU-sx-OmTwqPK8QvvlVuvYy9tk72fII7Qw"